# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uproc < Formula
  desc "Uproc CLI"
  homepage "https://github.com/uproc-io/uproc-cli"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.2/uproc.cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "22bd30b4ce1604166c3853e305610ed35d98adc49bbb7655b08b920ede9eff85"

      define_method(:install) do
        bin.install "uproc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.2/uproc.cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "3b98eb934191a752aaa675d50e3a4c3eba2a484eef842b466c0ec2e97acc657a"

      define_method(:install) do
        bin.install "uproc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.2/uproc.cli_0.2.2_linux_amd64.tar.gz"
      sha256 "b9a1073a5f249ea47dd6f8e17e1107c955083d85aef4f84327159d5cfbdb0490"
      define_method(:install) do
        bin.install "uproc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.2/uproc.cli_0.2.2_linux_arm64.tar.gz"
      sha256 "0411c1d0d1a9a68d5f63fe9c621d20745a8e203baeac5c117f403e610b2d601e"
      define_method(:install) do
        bin.install "uproc"
      end
    end
  end

  test do
    system "#{bin}/uproc --help"
  end
end
