# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uproc < Formula
  desc "Uproc CLI"
  homepage "https://github.com/uproc-io/uproc-cli"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.4/uproc.cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "0bfa85a500ae0b1a7320a7fea4fc34e712815845fdce0ddc0e6ce26c11f1cbd7"

      define_method(:install) do
        bin.install "uproc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.4/uproc.cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "53be5ac20965be10d81c51a9bc6631cfbb1ca88a6cb03b8cdc868fd0f74db422"

      define_method(:install) do
        bin.install "uproc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.4/uproc.cli_0.2.4_linux_amd64.tar.gz"
      sha256 "6a1df5e25cf8594d0e996a1cf4a5286cc894621f181cc2267b7856b07a64353f"
      define_method(:install) do
        bin.install "uproc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uproc-io/uproc-cli/releases/download/v0.2.4/uproc.cli_0.2.4_linux_arm64.tar.gz"
      sha256 "16c4d0e5677e3db58f85e85e4fc319b42f2a61a38266b0b3cf96f16299b14000"
      define_method(:install) do
        bin.install "uproc"
      end
    end
  end

  test do
    system "#{bin}/uproc --help"
  end
end
